name: "CI: pytest suite"

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: spack/setup-spack@v2
        with:
          buildcache: false
      
      - name: Run tests
        shell: spack-bash {0}
        run: |
          sudo rm -rf /usr/local &
          export SPACK_ROOT=$(realpath $(dirname $(which spack))/..)
          . source_me.sh
          spack unit-test --extension=helpers -m "not integration"
          # Run the long-running tests after we've run the short ones:
          spack unit-test --extension=helpers -m "integration"
